all: racine
	cd Dotted-web && npm run dev
	cd Dotted-back && docker compose up 

Clone: racine
	git clone https://github.com/3x0De/Dotted-web.git
	git clone https://github.com/3x0De/Dotted-back.git

Init: Clone
	cd Dotted-web && npm install
	cd Dotted-back && docker compose up --build


racine:
	cd ../

Clean: racine
	rm -fr Dotted-back Dotted-web